config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :links

  get 'home/index'
  root 'home#index'

  get '/l/:code' => "links#redirect"

  extend ApiRoutes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord

  belongs_to :user

  validates_presence_of :url
  validates_length_of :code, maximum: 7
  validates_length_of :url, maximum: 300
  validates_uniqueness_of :code
  validate :validate_url_format

  scope :top_links, -> { order(hits: :desc).limit(ENV.fetch('NO_OF_TOP_HITS', 100)) }

  before_save :gen_code

  def validate_url_format
    uri = URI.parse(url || '')
    errors.add(:url, I18n.t('links.invalid_format')) if uri.host.nil?
  end

  private

  def gen_code
    self.code = Shortener.new.code
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :links

  validates_length_of :api_key, maximum: 20

  before_save :gen_api_key

  private

  def gen_api_key
    self.api_key = Devise.friendly_token
  end
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

class Api::V1::BaseController < ApplicationController
  include AuthorizationHelper

  skip_before_action :verify_authenticity_token

  def params_paging
    params.permit(:page, :per).to_h.symbolize_keys
  end
end

app/controllers/api/v1/links_controller.rb
# frozen_string_literal: true

class Api::V1::LinksController < Api::V1::BaseController
  before_action :authorize_current_user

  def index
    links = Link.where(user: current_user).order(created_at: :desc).page(params_paging[:page]).per(params_paging[:per])
    render json: json_with_pagination(links)
  end

  def create
    link = current_user.links.create!(url: link_params[:url])
    render json: json_with_success(data: link)
  end

  private

  def link_params
    params.permit(:url)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ResponseHelper
  include ErrorsHandler
end

app/controllers/concerns/authorization_helper.rb
require 'json'

module AuthorizationHelper
  extend ActiveSupport::Concern

  protected

  def authorize_current_user
    return current_user if current_user

    raise ErrorsHandler::Forbidden
  end

  def current_user
    User.find_by(api_key: header_token)
  end

  def header_token
    request.headers['HTTP_AUTHORIZATION']
  end

end

app/controllers/concerns/errors_handler.rb
# frozen_string_literal: true

module ErrorsHandler
  extend ActiveSupport::Concern

  class Forbidden < StandardError; end

  included do
    rescue_from Forbidden, with: :handle_forbidden
    rescue_from ActionController::ParameterMissing, with: :handle_parameter_missing
    rescue_from ActiveRecord::RecordInvalid, with: :handle_record_invalid
  end

  protected

  def handle_forbidden
    render json: json_with_error(message: I18n.t("errors.forbidden")), status: :forbidden
  end

  def handle_parameter_missing
    render json: json_with_error(message: I18n.t("errors.parameters_missing")), status: :bad_request
  end

  def handle_record_invalid(exception)
    render json: json_with_error(
                   message: I18n.t("errors.record_invalid", record: humanized_model_name(exception.record.class.to_s)),
                   errors:  exception.record&.errors&.messages
                 ), status: :unprocessable_entity
  end

  private

  def humanized_model_name(model_name)
    model_name&.underscore&.humanize(keep_id_suffix: true) || "record"
  end
end

app/controllers/concerns/response_helper.rb
# frozen_string_literal: true

module ResponseHelper
  extend ActiveSupport::Concern

  def json_with_success(message: :success, data: nil)
    {
      code:    200,
      message: message,
      data:    data
    }
  end

  def json_with_error(message: :fail, errors: nil)
    {
      message: message,
      errors:  errors
    }
  end

  def json_with_pagination(data)
    pagination = {
      limit_value:  data.respond_to?(:limit_value) && data.limit_value ? data.limit_value : 0,
      current_page: data.respond_to?(:current_page) ? data.current_page : 1,
      next_page:    data.respond_to?(:next_page) ? data.next_page : nil,
      prev_page:    data.respond_to?(:prev_page) ? data.prev_page : nil,
      total_pages:  data.respond_to?(:total_pages) ? data.total_pages : 1
    }

    {
      pagination: pagination,
      items:      data
    }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @top_links = Link.top_links
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: :redirect
  before_action :set_link, only: %i[show edit update destroy]

  # GET /links or /links.json
  def index
    @links = Link.where(user: current_user).order(created_at: :desc)
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = current_user.links.create(link_params)

    if @link.persisted?
      @shortened_url = "#{request.base_url}/l/#{@link.code}"
      respond_to :js
    else
      render 'error.js.erb'
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    if @link.update(link_params)
      @shortened_url = "#{request.base_url}/l/#{@link.code}"
      render 'show'
    else
      render 'error.js.erb'
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, flash: {info: "Link was successfully destroyed."} }
      format.json { head :no_content }
    end
  end

  def redirect
    link = Link.find_by(code: params[:code])
    return redirect_to '/' unless link

    link.increment!(:hits)

    redirect_to link.url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>Top 100 most visited links</h1>

  <%= link_to 'New Link', new_link_path, class: 'btn btn-success' %>

  <table class="table">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">URL</th>
      <th scope="col">Hits</th>
    </tr>
    </thead>
    <tbody>
    <% @top_links.each_with_index do |link, i| %>
      <tr>
        <td> <%= i + 1 %> </td>
        <td>
          <%= link_to link.url, target: :_blank do %>
            <%= link.url %>
          <% end %>
        </td>
        <td> <%= link.hits %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spiderlink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, remote: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :url, 'URL' %>
  <%= form.text_field :url %>
  <%= form.submit %>
<% end %>

app/views/links/_link.html.erb
<div class="card-footer">
  <div class="alert alert-success">
    <b>Share this link to your friend: </b><a href=<%= link %>><%= link %></a>
  </div>
</div>

app/views/links/create.js.erb
var shortLink = document.getElementById('short-link');
var html = "<%= j render 'link', link: @shortened_url %>"
shortLink.innerHTML = html;

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/error.js.erb
var msg = "<%= @link.errors.full_messages.join('. ') << '.' %>";
var ele = document.getElementById('short-link');
ele.innerHTML = msg;

app/views/links/index.html.erb
<div class="container">

  <h1>Links</h1>

  <%= link_to 'New Link', new_link_path, class: 'btn btn-success' %>

  <table class="table">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">URL</th>
      <th scope="col">Created at</th>
      <th scope="col">Code</th>
      <th scope="col">Hits</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @links.each do |link| %>
      <tr>
        <td> <%= link.id %> </td>
        <td> <%= link.url %> </td>
        <td> <%= link.created_at %> </td>
        <td>
          <a href="l/<%= link.code %>">
            <%= link.code %>
          </a>
        </td>
        <td> <%= link.hits %> </td>
        <td>
          <%= link_to 'Show', link %>
          <%= link_to 'Edit', edit_link_path(link) %>
          <%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/links/new.html.erb
<div class="container">
  <div class="p-5">
    <div class="card">
      <div class="card-body">
        <h5>Input your link:</h5>

        <%#= render 'form', link: @link %>

        <%= form_for @link, remote: true do |form| %>
          <%= form.text_field :url, class: "form-control"  %>
          <%= form.submit "Create", class: 'btn btn-primary mt-3' %>
        <% end %>

        <div id="short-link"></div>
        <%#= link_to 'Back', links_path %>
      </div>
    </div>
  </div>
</div>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<%= @link.url %>
<%= @link.code %>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/shared/_flash.html.erb
<% flash.each do |name, message| %>
  <div class="alert alert-<%= name == 'notice' ? 'info' : name %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href=<%= links_path %> %>My links</a>
    </div>
    <div id="nav-user">
      <form class="form-inline pull-xs-right">
        <% if current_user %>
          Welcome <%= current_user.email %>. Your API key: <%= current_user.api_key %>
          <%= link_to "Sign out", destroy_user_session_path, :method => :get, class: 'nav-link' %>
        <% else %>
          <%= link_to "Log in", user_session_path, class: 'nav-link' %>
          <%= link_to "Register", new_user_registration_path, class: 'nav-link' %>
        <% end %>
      </form>
    </div>
  </div>
</nav>